# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_rc_impl <- function(seqs, type = "DNA") {
    .Call(`_fastrc_fast_rc_impl`, seqs, type)
}

